import {
  	ENV_BASE_URL,
	ENV_BASE_API,
	ENV_PLATFORM_ID,
	ENV_FILE_FOLDER,
	ENV_UPLOAD_FOLDER,
	ENV_SECRETFILE_FOLDER,
	ENV_MP_WECHAT_APPID,
	ENV_REGION_ID,
	ENV_REGION_DRUG,
	VUE_APP_PROCESS,
	DOMAIN_NAME,
	Software_Park,
	ENV_SECRETFILE_CARD,
	ENV_SECRETFILE_IDCARD,
	ENV_MP_APPLET_APPID
} from './env'

export const BASE = ENV_BASE_URL
export const BASE_URL = ENV_BASE_URL + ENV_BASE_API
export const FILE_URL = ENV_BASE_URL + ENV_FILE_FOLDER + '/'
export const SPMATE_FILE_URL = ENV_BASE_URL + ENV_BASE_API + ENV_FILE_FOLDER + '/'
export const UPLOAD_URL = ENV_BASE_URL + ENV_UPLOAD_FOLDER
export const SECRETFILE_URL = ENV_BASE_URL + ENV_SECRETFILE_FOLDER		//图片流接口
export const OCR_URL_CARD = ENV_BASE_URL + ENV_BASE_API + ENV_SECRETFILE_CARD		//OCR银行卡图片流接口
export const OCR_URL_IDCARD = ENV_BASE_URL + ENV_BASE_API + ENV_SECRETFILE_IDCARD		//OCR银行卡图片流接口
export const MP_WECHAT_APPID = ENV_MP_WECHAT_APPID		// 微信小程序appid
export const MP_APPLET_APPID = ENV_MP_APPLET_APPID		// 云闪付小程序appid
export const PLATFORM_ID = ENV_PLATFORM_ID
export const REGION_ID = ENV_REGION_ID
export const REGION_ID_DRUG = ENV_REGION_DRUG
export const EVN_APP_PROCESS = VUE_APP_PROCESS
export const BASE_DOMAIN_NAME = DOMAIN_NAME
export const BASE_Software_Park = Software_Park
